version: 2

builds:
  - binary: zohcli
    main: .
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^style:"
  groups:
    - title: Features
      regexp: '^feat'
    - title: Bug Fixes
      regexp: '^fix'
    - title: Refactoring
      regexp: '^refactor'
    - title: Testing
      regexp: '^test'
    - title: Other
      order: 999

release:
  github:
    owner: SeMmyT
    name: zohcli
